[pyprland]
plugins = ["scratchpads"]

[scratchpads.protonvpn]
command = "protonvpn-app"
class = "proton.vpn.app.gtk"
lazy = true
multi = false

[scratchpads.foot-dropterm]
command = "foot --app-id foot-dropterm --title foot-dropterm"
class = "foot-dropterm"
lazy = true
size = "50% 60%"
position = "50% 5%"
animation = "fromRight"

[scratchpads.foot-btop]
command = "foot --app-id foot-btop --title foot-btop -e btop"
class = "foot-btop"
lazy = true
size = "50% 70%"

[scratchpads.foot-nvtop]
command = "foot --app-id foot-nvtop --title foot-nvtop -e nvtop"
class = "foot-nvtop"
lazy = true
size = "50% 70%"
