[pyprland]
plugins = ["scratchpads"]

[scratchpads.term]
animation = "fromTop"
command = "foot --app-id foot-dropterm --title foot-dropterm"
class = "foot-dropterm"
size = "70% 70%"
margin = 50
pinned = false

[scratchpads.vpn]
command = "protonvpn-app"
class = "protonvpn-app"
size = "40% 60%"
margin = 50
lazy = true

[scratchpads.btop]
animation = "fromBottom"
command = "btop"
class = "btop-scratch"
size = "80% 80%"
margin = 50
lazy = true

[scratchpads.nvtop]
animation = "fromLeft"
command = "nvtop"
class = "nvtop-scratch"
size = "80% 80%"
margin = 50
lazy = true
